### ISSUE TITLE
Cached relations are not invalidated

### ISSUE THREAD

**Issue by k8n** [rinvex/laravel-cacheable#28]
CacheableEloquent caches relations data, but does not invalidate cache when the related models change. There is no indications in the documentation of how relationships are treated or if there are strategies to make caching work for relations.

**Comment by batFormat** [comment]
@k8n 

Maybe I certainly did not understand your problem.
I delete attribute (relation) values like this.

```
foreach ($model->{$attribute}()->get() as $attribute) {
    $attribute->delete();
}
```

**Comment by k8n** [comment]
Say, model A has a relation B (`$a->b`, b with ID 1). If A is cached and I do `B::find(1)->delete()`, `$a->b` would return the cached copy of the deleted model. I will write a test when I find a moment; for now I side-stepped the issue in my implementation.

**Comment by abishekrsrikaanth** [comment]
Are there any updates to this issue?

**Comment by Omranic** [comment]
@k8n  I'm not sure I understand the workflow of your code, since all caches are stored using cache tags, which is linked to the model, so once the model cache is flushed, everything related should be flushed accordingly.

If you still have this issue, and you can provide more explanation with code snippets to reproduce the issue, that would be great, so we can help more.
