### ISSUE TITLE
Forget cache all models

### ISSUE THREAD

**Issue by Krato** [rinvex/laravel-cacheable#7]
Hi, I have a process that makes a lot of changes.

How can I forget all models cache?

Thanks!

**Comment by noxify** [comment]
Hi,

it seems that this feature is currently not implemented.

I assume you mean something like `forgetAll()` or something like that.

Idea / Workaround:

1. get all models ( code snippet: http://stackoverflow.com/a/34054171 )
2. Initialize an empty model for each found model
3. Run the `forgetCache()` method for each initalized model

**Comment by Krato** [comment]
Ok. I will try.

Also, will be great to set if you want to use cache or not for some functions, and when ends, recache.

Thanks!

**Comment by noxify** [comment]
I hope i understood it correctly.

You have a model where the cacheable package is used.

You have a static variable where you can exclude a function from the cache:

```
protected $ignoreCache = ['created', 'updated'];
```

Is this correct?

Maybe, it's better to create a new issue / feature request for this.
If you have any ideas how to implement this, feel free to send a PR :)

**Comment by Omranic** [comment]
@Krato For the first question about forgetting all models cache, I don't see a real need to implement it by default since you still can do it as @noxify mentioned, and it's actually up to your app's logic which differs from one scenario to another 🙂 

And for the other feature request about ignoring some methods, that's a good idea. I'll be happy to accept your PR, or you can open a new issue with your feature proposal 👍
